### PR TITLE
fix: fetch token icons from multiple lists

### LINKED ISSUE #38: Fix the token list images
Currently, a lot of tokens in dxstats do not have images, would be good to fix those.

### PR DESCRIPTION
**Pull request by guerrap**
# Summary

Fixes #38 

Try to get tokens logos from multiple lists.

# How To Test

1.  In all the pages displaying tokens
- [ ] More token icons should now be visible

# Background

I've added the same tokens lists that swapr-dapp is using, but there are still tokens without icons because I couldn't find any token list that included them.

### CODE REVIEW

File: src/contexts/Application.js [hunk 1]
```diff
@@ -333,7 +357,42 @@ export function useBadImageUrlsUpdater() {
...
+          continue;
+        }
+      }
+
+      updateTokenLists(tokensLists);
+    }
+
+    if (!state.TOKEN_LISTS || state.TOKEN_LISTS.length === 0) {
+      fetchTokensLists();
+    }
```
Comment (wixzi) [inline src/contexts/Application.js:394]:
```suggestion
    if (state.TOKEN_LISTS.length === 0) {
      fetchTokensLists();
    }
```
```suggestion
    if (!state.TOKEN_LISTS || state.TOKEN_LISTS.length === 0) {
      fetchTokensLists();
    }
```

Comment (wixzi) [inline src/contexts/Application.js:394]:
```suggestion
    if (state.TOKEN_LISTS.length === 0) {
      fetchTokensLists();
    }
```
```suggestion
    if (!state.TOKEN_LISTS || state.TOKEN_LISTS.length === 0) {
      fetchTokensLists();
    }
```

**Comment by wixzi** [comment]
@guerrap Can you share an image of what logos you fixed in which page?

File: src/App.js [hunk 2]
```diff
@@ -112,7 +113,9 @@ function App() {
       {globalData &&
       Object.keys(globalData).length > 0 &&
       globalChartData &&
-      Object.keys(globalChartData).length > 0 ? (
+      Object.keys(globalChartData).length > 0 &&
+      tokensLists &&
+      tokensLists.length > 0 ? (
```
Comment (wixzi) [inline src/App.js:118]: We are removing this check in App.js. So move this to TokenList page loader

**Review by wixzi — CHANGES_REQUESTED** [review]

File: src/App.js (hunk 2 above)
Comment (guerrap) [reply src/App.js:118]: Maybe It's better if I fix this after we merge your PR about the loading changes?

**Comment by guerrap** [comment]
The network selected is Arbitrum but the changes take effect on every network.

### Overview page
arbi-top-pairs
arbi-top-pairs-pair

### Tokens page
tokens-page

### Pairs page
pairs-page

### Farming page
farming

And the same goes for the Account page,

File: src/App.js (hunk 2 above)
Comment (guerrap) [reply src/App.js:118]: I thought about it, and maybe the whole app should wait for the tokens lists to be fetched since the token logos are used almost everywhere, what do you think? The http calls to fetch the tokens are all pretty fast

File: src/utils/index.js [hunk 3]
```diff
@@ -634,3 +634,25 @@ export function getStakedAmountUSD(campaign, nativeCurrencyUSDPrice, nativeCurre
...
+export function uriToHttp(uri) {
+  const protocol = uri.split(':')[0].toLowerCase();
+  switch (protocol) {
+    case 'https':
+      return [uri];
+    case 'http':
+      return ['https' + uri.substr(4), uri];
+    case 'ipfs':
+      const hash = uri.match(/^ipfs:(\/\/)?(.*)$/i)?.[2];
+      return [`https://ipfs.io/ipfs/${hash}/`, `https://ipfs.io/ipfs/${hash}/`];
```
Comment (wixzi) [inline src/utils/index.js:651]: why are you returning the same `https://ipfs.io/ipfs/${hash}/` twice?

File: src/App.js (hunk 2 above)
Comment (wixzi) [reply src/App.js]: I think most of links in the URL array is getting 404. I will give a check today evening and see. If its fast we can wait till it loads.

File: src/utils/index.js (hunk 3 above)
Comment (guerrap) [reply src/utils/index.js:651]: Actually I think I can remove this function, since all the URLs in the list are http

Comment (guerrap) [reply src/utils/index.js:651]: Dind't notice that, that should be http

File: src/App.js (hunk 2 above)
Comment (guerrap) [reply src/App.js]: The 404s were caused by searching the images on trustwallet, but I removed that since it was redundant, all the icons are included in the pre-loaded lists

**Review by wixzi — APPROVED** [review]
